import {MigrationInterface, QueryRunner} from "typeorm";

export class InitialMigration1540249452286 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `country` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `address` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `addressLine1` varchar(255) NULL, `addressLine2` varchar(255) NULL, `city` varchar(255) NULL, `state` varchar(255) NOT NULL, `countryId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `media` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` int NOT NULL, `type` int NOT NULL, `note` varchar(255) NULL, `userId` varchar(255) NULL, `companyId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `product` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, `categoryId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `category` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `urlToken` varchar(255) NOT NULL, `logoUrl` varchar(255) NULL, `postalBox` int NULL, `phone` varchar(255) NOT NULL, `website` varchar(255) NULL, `email` varchar(255) NOT NULL, `backgroundCheck` tinyint NOT NULL, `noBackgroundCheckReason` varchar(255) NULL, `registrationType` int NOT NULL, `registrationNumber` varchar(255) NOT NULL, `registrationDate` datetime NOT NULL, `taxpayersIdentificationNumber` int NULL, `vatRegistrationNumber` int NULL, `averageAnnualContractValue` double NOT NULL, `highestSingularContractValue` double NOT NULL, `productsDescription` varchar(500) NOT NULL, `verified` tinyint NOT NULL, `addressId` varchar(255) NULL, `categoryId` varchar(255) NULL, UNIQUE INDEX `REL_3737905699894299444476dd79` (`addressId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `view` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` varchar(255) NULL, `viewedById` varchar(255) NULL, UNIQUE INDEX `REL_81b9a8421ae190ecf67ba04486` (`viewedById`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `connection` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `status` int NOT NULL, `userId` varchar(255) NULL, `connectedToId` varchar(255) NULL, UNIQUE INDEX `REL_9c8dcb891f6b5e2599bf48c0b6` (`connectedToId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `experience` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `role` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `organization` varchar(255) NOT NULL, `startDate` datetime NOT NULL, `endDate` datetime NULL, `current` tinyint NOT NULL, `companyLogoUrl` varchar(255) NULL, `userId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `skill` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, UNIQUE INDEX `IDX_0f49a593960360f6f85b692aca` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `article_category` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `name` varchar(255) NOT NULL, `title` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `timeline_photo` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `url` varchar(255) NOT NULL, `isDisabled` tinyint NOT NULL, `commentsCount` int NOT NULL DEFAULT 0, `likesCount` int NOT NULL DEFAULT 0, `authorId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `like` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `userId` varchar(255) NULL, `timelineUpdateId` varchar(255) NULL, `timelinePhotoId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `timeline_update` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `content` varchar(255) NOT NULL, `isDisabled` tinyint NOT NULL, `commentsCount` int NOT NULL DEFAULT 0, `likesCount` int NOT NULL DEFAULT 0, `authorId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `discussion` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `urlToken` varchar(255) NOT NULL, `commentsCount` int NOT NULL DEFAULT 0, `authorId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `webinar` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `cpdPoints` int NOT NULL DEFAULT 0, `topic` varchar(255) NOT NULL, `description` varchar(1000) NOT NULL, `urlToken` varchar(15) NOT NULL, `startDateTime` datetime NOT NULL, `createAnnouncement` tinyint NOT NULL, `status` int NOT NULL, `authorId` varchar(255) NULL, `anchorId` varchar(255) NULL, `transcriptId` varchar(255) NULL, UNIQUE INDEX `REL_e966510fbd3c92818133770d1a` (`anchorId`), UNIQUE INDEX `REL_8e84d1ff323e24514faef3e2fb` (`transcriptId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `comment` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `content` varchar(255) NOT NULL, `authorId` varchar(255) NULL, `parentCommentId` varchar(255) NULL, `articleId` varchar(255) NULL, `discussionId` varchar(255) NULL, `timelineUpdateId` varchar(255) NULL, `timelinePhotoId` varchar(255) NULL, `webinarId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `article` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `title` varchar(255) NOT NULL, `urlToken` varchar(255) NOT NULL, `synopsis` varchar(200) NOT NULL, `body` varchar(255) NOT NULL, `isPublished` tinyint NOT NULL, `status` int NOT NULL, `authorId` varchar(255) NULL, `featuredImageId` varchar(255) NULL, `categoryId` varchar(255) NULL, UNIQUE INDEX `REL_04a298d4b0c32a2ad4cb3f736f` (`featuredImageId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `resource` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `isPublished` tinyint NOT NULL, `title` varchar(255) NOT NULL, `description` varchar(500) NULL, `purchaseUrl` varchar(255) NOT NULL, `userId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `certificate` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `issuer` varchar(255) NOT NULL, `certificateNumber` varchar(255) NOT NULL, `dateOfIssue` datetime NOT NULL, `issuerLogoUrl` varchar(255) NULL, `userId` varchar(255) NULL, `mediaId` varchar(255) NULL, UNIQUE INDEX `REL_ed83e3206ba59e126939f198a9` (`mediaId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `notification` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `content` varchar(255) NOT NULL, `userId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `type` int NOT NULL, `firstName` varchar(255) NOT NULL, `lastName` varchar(255) NOT NULL, `urlToken` varchar(255) NOT NULL, `phone` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `facebookUrl` varchar(255) NULL, `linkedInUrl` varchar(255) NULL, `googlePlusUrl` varchar(255) NULL, `twitterUrl` varchar(255) NULL, `cpdPoints` int NOT NULL DEFAULT 0, `description` varchar(500) NULL, `addressId` varchar(255) NULL, `latestExperienceId` varchar(255) NULL, `profilePhotoId` varchar(255) NULL, `companyId` varchar(255) NULL, `skillsId` varchar(255) NULL, UNIQUE INDEX `IDX_e12875dfb3b1d92d7d7c5377e2` (`email`), UNIQUE INDEX `REL_217ba147c5de6c107f2fa7fa27` (`addressId`), UNIQUE INDEX `REL_e814789f2ee74f556a538a3042` (`latestExperienceId`), UNIQUE INDEX `REL_87b40c02a70fd210bead07c854` (`profilePhotoId`), UNIQUE INDEX `REL_86586021a26d1180b0968f9850` (`companyId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `announcement` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `content` varchar(255) NOT NULL, `isPublished` tinyint NOT NULL, `authorId` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `job` (`id` varchar(255) NOT NULL, `createdDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `modifiedDate` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `urlToken` varchar(15) NOT NULL, `isPublished` tinyint NOT NULL, `title` varchar(255) NOT NULL, `type` int NOT NULL, `organizationName` varchar(255) NOT NULL, `applicationUrl` varchar(255) NOT NULL, `description` varchar(1000) NOT NULL, `roles` varchar(1000) NOT NULL, `requirements` varchar(1000) NOT NULL, `viewCount` int NOT NULL DEFAULT 0, `authorId` varchar(255) NULL, `addressId` varchar(255) NULL, UNIQUE INDEX `REL_3110ec3566692f54d21238fb43` (`addressId`), PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_products_product` (`companyId` varchar(255) NOT NULL, `productId` varchar(255) NOT NULL, PRIMARY KEY (`companyId`, `productId`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `webinar_participants_user` (`webinarId` varchar(255) NOT NULL, `userId` varchar(255) NOT NULL, PRIMARY KEY (`webinarId`, `userId`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `address` ADD CONSTRAINT `FK_d87215343c3a3a67e6a0b7f3ea9` FOREIGN KEY (`countryId`) REFERENCES `country`(`id`)");
        await queryRunner.query("ALTER TABLE `media` ADD CONSTRAINT `FK_0db866835bf356d896e1892635d` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `media` ADD CONSTRAINT `FK_0007e36c19806357e395578a859` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`)");
        await queryRunner.query("ALTER TABLE `product` ADD CONSTRAINT `FK_ff0c0301a95e517153df97f6812` FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`)");
        await queryRunner.query("ALTER TABLE `company` ADD CONSTRAINT `FK_3737905699894299444476dd79c` FOREIGN KEY (`addressId`) REFERENCES `address`(`id`)");
        await queryRunner.query("ALTER TABLE `company` ADD CONSTRAINT `FK_4b47f280258a2e73f5c44497e83` FOREIGN KEY (`categoryId`) REFERENCES `category`(`id`)");
        await queryRunner.query("ALTER TABLE `view` ADD CONSTRAINT `FK_c6af9853ff6a60d2e80dd8b3af9` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `view` ADD CONSTRAINT `FK_81b9a8421ae190ecf67ba044869` FOREIGN KEY (`viewedById`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `connection` ADD CONSTRAINT `FK_3b35155c2968acced66fc326aea` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `connection` ADD CONSTRAINT `FK_9c8dcb891f6b5e2599bf48c0b6d` FOREIGN KEY (`connectedToId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `experience` ADD CONSTRAINT `FK_cbfb1d1219454c9b45f1b3c4274` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `timeline_photo` ADD CONSTRAINT `FK_8a16af1827a2aa6d986fd36cb8d` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `like` ADD CONSTRAINT `FK_e8fb739f08d47955a39850fac23` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `like` ADD CONSTRAINT `FK_60948471855c2e2cf5874534c75` FOREIGN KEY (`timelineUpdateId`) REFERENCES `timeline_update`(`id`)");
        await queryRunner.query("ALTER TABLE `like` ADD CONSTRAINT `FK_ee380ccadd87153599e6da0c720` FOREIGN KEY (`timelinePhotoId`) REFERENCES `timeline_photo`(`id`)");
        await queryRunner.query("ALTER TABLE `timeline_update` ADD CONSTRAINT `FK_1a80ee9a44f3d22baeed74c1cbe` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `discussion` ADD CONSTRAINT `FK_79b00713c1e8f1b9e1984cf9043` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `webinar` ADD CONSTRAINT `FK_ecc98dfd3a0a092e1df84dba0ee` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `webinar` ADD CONSTRAINT `FK_e966510fbd3c92818133770d1af` FOREIGN KEY (`anchorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `webinar` ADD CONSTRAINT `FK_8e84d1ff323e24514faef3e2fb8` FOREIGN KEY (`transcriptId`) REFERENCES `media`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_276779da446413a0d79598d4fbd` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_73aac6035a70c5f0313c939f237` FOREIGN KEY (`parentCommentId`) REFERENCES `comment`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c20404221e5c125a581a0d90c0e` FOREIGN KEY (`articleId`) REFERENCES `article`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_439477beb3a538163fbec09f144` FOREIGN KEY (`discussionId`) REFERENCES `discussion`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_e2c845f81f94db42394ff7e19ea` FOREIGN KEY (`timelineUpdateId`) REFERENCES `timeline_update`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_2fb1655223b64fe67da912d8f07` FOREIGN KEY (`timelinePhotoId`) REFERENCES `timeline_photo`(`id`)");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_2f10ba7fdf730bc0077110ecbea` FOREIGN KEY (`webinarId`) REFERENCES `webinar`(`id`)");
        await queryRunner.query("ALTER TABLE `article` ADD CONSTRAINT `FK_a9c5f4ec6cceb1604b4a3c84c87` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `article` ADD CONSTRAINT `FK_04a298d4b0c32a2ad4cb3f736fe` FOREIGN KEY (`featuredImageId`) REFERENCES `media`(`id`)");
        await queryRunner.query("ALTER TABLE `article` ADD CONSTRAINT `FK_12824e4598ee46a0992d99ba553` FOREIGN KEY (`categoryId`) REFERENCES `article_category`(`id`)");
        await queryRunner.query("ALTER TABLE `resource` ADD CONSTRAINT `FK_77a300816e77fa9fdca6879c4d1` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `certificate` ADD CONSTRAINT `FK_52422eba9e5b9d779d3e173a25d` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `certificate` ADD CONSTRAINT `FK_ed83e3206ba59e126939f198a9e` FOREIGN KEY (`mediaId`) REFERENCES `media`(`id`)");
        await queryRunner.query("ALTER TABLE `notification` ADD CONSTRAINT `FK_1ced25315eb974b73391fb1c81b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_217ba147c5de6c107f2fa7fa271` FOREIGN KEY (`addressId`) REFERENCES `address`(`id`)");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_e814789f2ee74f556a538a30423` FOREIGN KEY (`latestExperienceId`) REFERENCES `experience`(`id`)");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_87b40c02a70fd210bead07c854c` FOREIGN KEY (`profilePhotoId`) REFERENCES `media`(`id`)");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_86586021a26d1180b0968f98502` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`)");
        await queryRunner.query("ALTER TABLE `user` ADD CONSTRAINT `FK_0e51e612eb9ed2fa5ac4f44c7e1` FOREIGN KEY (`skillsId`) REFERENCES `skill`(`id`)");
        await queryRunner.query("ALTER TABLE `announcement` ADD CONSTRAINT `FK_15ae13897e2eb2c8e9d932b4a41` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `job` ADD CONSTRAINT `FK_f3e6789f2c84e5fdd2305096cf4` FOREIGN KEY (`authorId`) REFERENCES `user`(`id`)");
        await queryRunner.query("ALTER TABLE `job` ADD CONSTRAINT `FK_3110ec3566692f54d21238fb43b` FOREIGN KEY (`addressId`) REFERENCES `address`(`id`)");
        await queryRunner.query("ALTER TABLE `company_products_product` ADD CONSTRAINT `FK_38ddc627843048b955a5270c3ea` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE CASCADE");
        await queryRunner.query("ALTER TABLE `company_products_product` ADD CONSTRAINT `FK_cc4534a71a5bc6bc674d2321111` FOREIGN KEY (`productId`) REFERENCES `product`(`id`) ON DELETE CASCADE");
        await queryRunner.query("ALTER TABLE `webinar_participants_user` ADD CONSTRAINT `FK_11291f7ef2ed6a4e7a6a34167d6` FOREIGN KEY (`webinarId`) REFERENCES `webinar`(`id`) ON DELETE CASCADE");
        await queryRunner.query("ALTER TABLE `webinar_participants_user` ADD CONSTRAINT `FK_0660dd65a72fb6a017769789f24` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `webinar_participants_user` DROP FOREIGN KEY `FK_0660dd65a72fb6a017769789f24`");
        await queryRunner.query("ALTER TABLE `webinar_participants_user` DROP FOREIGN KEY `FK_11291f7ef2ed6a4e7a6a34167d6`");
        await queryRunner.query("ALTER TABLE `company_products_product` DROP FOREIGN KEY `FK_cc4534a71a5bc6bc674d2321111`");
        await queryRunner.query("ALTER TABLE `company_products_product` DROP FOREIGN KEY `FK_38ddc627843048b955a5270c3ea`");
        await queryRunner.query("ALTER TABLE `job` DROP FOREIGN KEY `FK_3110ec3566692f54d21238fb43b`");
        await queryRunner.query("ALTER TABLE `job` DROP FOREIGN KEY `FK_f3e6789f2c84e5fdd2305096cf4`");
        await queryRunner.query("ALTER TABLE `announcement` DROP FOREIGN KEY `FK_15ae13897e2eb2c8e9d932b4a41`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_0e51e612eb9ed2fa5ac4f44c7e1`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_86586021a26d1180b0968f98502`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_87b40c02a70fd210bead07c854c`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_e814789f2ee74f556a538a30423`");
        await queryRunner.query("ALTER TABLE `user` DROP FOREIGN KEY `FK_217ba147c5de6c107f2fa7fa271`");
        await queryRunner.query("ALTER TABLE `notification` DROP FOREIGN KEY `FK_1ced25315eb974b73391fb1c81b`");
        await queryRunner.query("ALTER TABLE `certificate` DROP FOREIGN KEY `FK_ed83e3206ba59e126939f198a9e`");
        await queryRunner.query("ALTER TABLE `certificate` DROP FOREIGN KEY `FK_52422eba9e5b9d779d3e173a25d`");
        await queryRunner.query("ALTER TABLE `resource` DROP FOREIGN KEY `FK_77a300816e77fa9fdca6879c4d1`");
        await queryRunner.query("ALTER TABLE `article` DROP FOREIGN KEY `FK_12824e4598ee46a0992d99ba553`");
        await queryRunner.query("ALTER TABLE `article` DROP FOREIGN KEY `FK_04a298d4b0c32a2ad4cb3f736fe`");
        await queryRunner.query("ALTER TABLE `article` DROP FOREIGN KEY `FK_a9c5f4ec6cceb1604b4a3c84c87`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_2f10ba7fdf730bc0077110ecbea`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_2fb1655223b64fe67da912d8f07`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_e2c845f81f94db42394ff7e19ea`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_439477beb3a538163fbec09f144`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c20404221e5c125a581a0d90c0e`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_73aac6035a70c5f0313c939f237`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_276779da446413a0d79598d4fbd`");
        await queryRunner.query("ALTER TABLE `webinar` DROP FOREIGN KEY `FK_8e84d1ff323e24514faef3e2fb8`");
        await queryRunner.query("ALTER TABLE `webinar` DROP FOREIGN KEY `FK_e966510fbd3c92818133770d1af`");
        await queryRunner.query("ALTER TABLE `webinar` DROP FOREIGN KEY `FK_ecc98dfd3a0a092e1df84dba0ee`");
        await queryRunner.query("ALTER TABLE `discussion` DROP FOREIGN KEY `FK_79b00713c1e8f1b9e1984cf9043`");
        await queryRunner.query("ALTER TABLE `timeline_update` DROP FOREIGN KEY `FK_1a80ee9a44f3d22baeed74c1cbe`");
        await queryRunner.query("ALTER TABLE `like` DROP FOREIGN KEY `FK_ee380ccadd87153599e6da0c720`");
        await queryRunner.query("ALTER TABLE `like` DROP FOREIGN KEY `FK_60948471855c2e2cf5874534c75`");
        await queryRunner.query("ALTER TABLE `like` DROP FOREIGN KEY `FK_e8fb739f08d47955a39850fac23`");
        await queryRunner.query("ALTER TABLE `timeline_photo` DROP FOREIGN KEY `FK_8a16af1827a2aa6d986fd36cb8d`");
        await queryRunner.query("ALTER TABLE `experience` DROP FOREIGN KEY `FK_cbfb1d1219454c9b45f1b3c4274`");
        await queryRunner.query("ALTER TABLE `connection` DROP FOREIGN KEY `FK_9c8dcb891f6b5e2599bf48c0b6d`");
        await queryRunner.query("ALTER TABLE `connection` DROP FOREIGN KEY `FK_3b35155c2968acced66fc326aea`");
        await queryRunner.query("ALTER TABLE `view` DROP FOREIGN KEY `FK_81b9a8421ae190ecf67ba044869`");
        await queryRunner.query("ALTER TABLE `view` DROP FOREIGN KEY `FK_c6af9853ff6a60d2e80dd8b3af9`");
        await queryRunner.query("ALTER TABLE `company` DROP FOREIGN KEY `FK_4b47f280258a2e73f5c44497e83`");
        await queryRunner.query("ALTER TABLE `company` DROP FOREIGN KEY `FK_3737905699894299444476dd79c`");
        await queryRunner.query("ALTER TABLE `product` DROP FOREIGN KEY `FK_ff0c0301a95e517153df97f6812`");
        await queryRunner.query("ALTER TABLE `media` DROP FOREIGN KEY `FK_0007e36c19806357e395578a859`");
        await queryRunner.query("ALTER TABLE `media` DROP FOREIGN KEY `FK_0db866835bf356d896e1892635d`");
        await queryRunner.query("ALTER TABLE `address` DROP FOREIGN KEY `FK_d87215343c3a3a67e6a0b7f3ea9`");
        await queryRunner.query("DROP TABLE `webinar_participants_user`");
        await queryRunner.query("DROP TABLE `company_products_product`");
        await queryRunner.query("DROP INDEX `REL_3110ec3566692f54d21238fb43` ON `job`");
        await queryRunner.query("DROP TABLE `job`");
        await queryRunner.query("DROP TABLE `announcement`");
        await queryRunner.query("DROP INDEX `REL_86586021a26d1180b0968f9850` ON `user`");
        await queryRunner.query("DROP INDEX `REL_87b40c02a70fd210bead07c854` ON `user`");
        await queryRunner.query("DROP INDEX `REL_e814789f2ee74f556a538a3042` ON `user`");
        await queryRunner.query("DROP INDEX `REL_217ba147c5de6c107f2fa7fa27` ON `user`");
        await queryRunner.query("DROP INDEX `IDX_e12875dfb3b1d92d7d7c5377e2` ON `user`");
        await queryRunner.query("DROP TABLE `user`");
        await queryRunner.query("DROP TABLE `notification`");
        await queryRunner.query("DROP INDEX `REL_ed83e3206ba59e126939f198a9` ON `certificate`");
        await queryRunner.query("DROP TABLE `certificate`");
        await queryRunner.query("DROP TABLE `resource`");
        await queryRunner.query("DROP INDEX `REL_04a298d4b0c32a2ad4cb3f736f` ON `article`");
        await queryRunner.query("DROP TABLE `article`");
        await queryRunner.query("DROP TABLE `comment`");
        await queryRunner.query("DROP INDEX `REL_8e84d1ff323e24514faef3e2fb` ON `webinar`");
        await queryRunner.query("DROP INDEX `REL_e966510fbd3c92818133770d1a` ON `webinar`");
        await queryRunner.query("DROP TABLE `webinar`");
        await queryRunner.query("DROP TABLE `discussion`");
        await queryRunner.query("DROP TABLE `timeline_update`");
        await queryRunner.query("DROP TABLE `like`");
        await queryRunner.query("DROP TABLE `timeline_photo`");
        await queryRunner.query("DROP TABLE `article_category`");
        await queryRunner.query("DROP INDEX `IDX_0f49a593960360f6f85b692aca` ON `skill`");
        await queryRunner.query("DROP TABLE `skill`");
        await queryRunner.query("DROP TABLE `experience`");
        await queryRunner.query("DROP INDEX `REL_9c8dcb891f6b5e2599bf48c0b6` ON `connection`");
        await queryRunner.query("DROP TABLE `connection`");
        await queryRunner.query("DROP INDEX `REL_81b9a8421ae190ecf67ba04486` ON `view`");
        await queryRunner.query("DROP TABLE `view`");
        await queryRunner.query("DROP INDEX `REL_3737905699894299444476dd79` ON `company`");
        await queryRunner.query("DROP TABLE `company`");
        await queryRunner.query("DROP TABLE `category`");
        await queryRunner.query("DROP TABLE `product`");
        await queryRunner.query("DROP TABLE `media`");
        await queryRunner.query("DROP TABLE `address`");
        await queryRunner.query("DROP TABLE `country`");
    }

}
